#!/bin/bash

echo "Removing old site directory"
rm -r _site

echo "Jekyll: Building"
jekyll build

echo "removing stray scripts from build"
rm _site/deploy

echo "Syncing w/ bucket"
aws s3 sync _site s3://raid-report.immdefense.org/ --profile fidiego
